# Generated by Django 3.1.7 on 2021-03-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20210320_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
