# Generated by Django 3.2.1 on 2021-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_callhistorymodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='phone_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
