# Generated by Django 3.2.1 on 2021-05-05 10:52

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_alter_phonemodel_phone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='aadhaar_id',
            field=models.BigIntegerField(null=True, verbose_name='Aadhaar Card ID'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
