# Generated by Django 3.2.1 on 2021-05-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_auto_20210505_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='country',
        ),
    ]
