# Generated by Django 3.2.1 on 2021-05-05 11:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_remove_phonemodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
